services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fadly-app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    
  nginx:
    image: nginx:stable
    container_name: fadly-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
